---
kind: pipeline
name: Build

platform:
  os: linux
  arch: amd64

steps:

- name: build
  pull: never
  image: cppnumericalsolver2
  commands:
  - /root/bin/bazel run simple


---
kind: signature
hmac: 27088188ae1ab304dea0a156a1a8de819a130dcba1d71268378f9f6e11cbe66b

...
